name = "PolygonIO"
uuid = "8d21102f-33ed-495a-9a0c-ac543572a703"
authors = ["PyDataBlog <bbrenyah@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
